export const userData = [
    {
        id: 1,
        status: "Pending",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                imageUrl: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                name: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 2,
        status: "Failed",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                imageUrl: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                name: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 3,
        status: "Pending",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                imageUrl: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                name: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 4,
        status: "Failed",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                imageUrl: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                name: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 5,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                imageUrl: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                name: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
    {
        id: 6,
        status: "Successful",
        customerName: "Jimoha Lawal Odutman",
        createdAt: "Mon, 4/18/2024 - 04:45 AM",
        transaction: {
            id: "123TWX5Y33456",
            method: "",
            amount: "₦780,000",
            type: "Bank Transfer",
            bank: {
                name: "Guaranty Trust Bank",
                image: "https://flagcdn.com/au.svg",
            },
        },
        action: {
            isAssigned: "true",
            customer: {
                imageUrl: "Jimoh Lawal Olafimihan",
            },
            staffAssigned: {
                name: "Oluseye John",
                date: "Mon, 4/19/2024",
                time: "09: 45 AM",
                // imageUrl: Avatar,
                staffMessage: "Reviewed to be approved.",
            },
        },
    },
];

export const dummyUser = [
    {
        currentAddress: "02055 Nina Expressway, Walton, NJ 57424",
        currentLoc: [-59.826871, -92.428323],
        dateCreated: "05 March 2024 at 13:54:12 UTC+1",
        email: "daugherty.laila@example.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-9b9825fd:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Kimberly Rowe",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: false,
        onboardingLevel: "identityVerification",
        password:
            "e6cf3415c0e2b0c6013a84e569af49dc9278e6364224fefc3c49d15ae7470056",
        phoneNumber: "(046) 892-2831",
        profilePhoto:
            "https://firebasestorage.googleapis.com/v0/b/projob-server.appspot.com/o/passportPhotographs%2F3P9mWnmBvnYslXFGtFXZXjhlWHp2%2Fgs34kvz3q9.jpg?alt=media&token=70ab2f92-e0c3-4d0f-bbde-01045ba5dd82",
        referralCode: "mkg9012",
        role: "Plumber",
        userId: "62222b4f19b54ea48358bfb05cfbc18f",
        userType: "client",
    },
    {
        currentAddress: "63870 Williams Wall, West Amybury, WY 41382",
        currentLoc: [-3.149024, 125.632861],
        dateCreated: "14 August 2024 at 21:04:44 UTC+1",
        email: "shields.carter@example.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-32dfda08:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Michael Jones",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "workProof",
        password:
            "f004c3273de9f327db60d07e6e23dcbf887a962ce89df4f202489c344f343de9",
        phoneNumber: "(370) 448-0527",
        profilePhoto: "",
        referralCode: "pzx4579",
        role: "Electrician",
        userId: "882be1a018d64eb68f58d2e7386d8009",
        userType: "provider",
    },
    {
        dateCreated: "29 July 2024 at 20:20:02 UTC+1",
        email: "Staimars2@gmail.com",
        fullName: "Staci Mars",
        password:
            "d46346972f4735c699e1e690eb75840fb1e54b15607577156fd272b6e7689851",
        phoneNumber: "+2347043290467",
        referralCode: "sta23r31",
        userId: "2sFWr427zpPnFz0mZ8eb49zZ1773",
        userType: "client",
    },
    {
        currentAddress: "12 Banana Island, Lagos, Nigeria",
        currentLoc: [6.4443145, 3.4194162],
        dateCreated: "18 March 2024 at 15:12:30 UTC+1",
        email: "jane.smith@gmail.com",
        fcmToken: "fcmToken2:APA91bG....",
        fullName: "Jane Smith",
        gender: "Female",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "identityVerification",
        password: "c48de512a...",
        phoneNumber: "+2348081234567",
        profilePhoto: "https://example.com/photo2.jpg",
        referralCode: "jane456",
        role: "Graphic Designer",
        userId: "user789012",
        userType: "client",
    },
    {
        currentAddress: "4 Broad Street, Abuja, Nigeria",
        currentLoc: [9.057851, 7.49508],
        dateCreated: "22 April 2024 at 10:00:00 UTC+1",
        email: "emma.williams@gmail.com",
        fcmToken: "fcmToken3:APA91bH....",
        fullName: "Emma Williams",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: false,
        onboardingLevel: "workProof",
        password: "e89df452b9...",
        phoneNumber: "+2349098765432",
        profilePhoto: "https://example.com/photo3.jpg",
        referralCode: "emma789",
        role: "Tutor",
        userId: "user345678",
        userType: "provider",
    },
    {
        currentAddress: "56 Garki, Abuja, Nigeria",
        currentLoc: [9.054267, 7.488566],
        dateCreated: "5 May 2024 at 14:25:40 UTC+1",
        email: "alex.brown@gmail.com",
        fcmToken: "fcmToken4:APA91bH....",
        fullName: "Alex Brown",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "profileSetup",
        password: "c92ab543df...",
        phoneNumber: "+2348123456789",
        profilePhoto: "https://example.com/photo4.jpg",
        referralCode: "alex234",
        role: "Plumber",
        userId: "user567890",
        userType: "provider",
    },
    {
        currentAddress: "10 Trans-Amadi, Port Harcourt, Nigeria",
        currentLoc: [4.815554, 7.049844],
        dateCreated: "10 June 2024 at 11:20:50 UTC+1",
        email: "lucy.green@gmail.com",
        fcmToken: "fcmToken5:APA91bH....",
        fullName: "Lucy Green",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "completed",
        password: "d91fb543ce...",
        phoneNumber: "+2348061234567",
        profilePhoto: "https://example.com/photo5.jpg",
        referralCode: "lucy567",
        role: "Chef",
        userId: "user7890123",
        userType: "provider",
    },
    {
        currentAddress: "22 Lekki Phase 1, Lagos, Nigeria",
        currentLoc: [6.4570576, 3.6015215],
        dateCreated: "15 July 2024 at 09:45:30 UTC+1",
        email: "chris.johnson@gmail.com",
        fcmToken: "fcmToken6:APA91bG....",
        fullName: "Chris Johnson",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "profileSetup",
        password: "f23ac452de...",
        phoneNumber: "+2347023456789",
        profilePhoto: "https://example.com/photo6.jpg",
        referralCode: "chris678",
        role: "Driver",
        userId: "user8901234",
        userType: "client",
    },
    {
        currentAddress: "8 Aba Road, Port Harcourt, Nigeria",
        currentLoc: [4.797016, 7.013506],
        dateCreated: "25 August 2024 at 13:30:20 UTC+1",
        email: "sophia.adams@gmail.com",
        fcmToken: "fcmToken7:APA91bH....",
        fullName: "Sophia Adams",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: false,
        onboardingLevel: "workProof",
        password: "d59ac542be...",
        phoneNumber: "+2347081234567",
        profilePhoto: "https://example.com/photo7.jpg",
        referralCode: "sophia789",
        role: "Hairdresser",
        userId: "user1234567",
        userType: "provider",
    },
    {
        currentAddress: "35 Ikoyi Crescent, Lagos, Nigeria",
        currentLoc: [6.4482922, 3.421713],
        dateCreated: "30 September 2024 at 18:15:45 UTC+1",
        email: "daniel.martin@gmail.com",
        fcmToken: "fcmToken8:APA91bG....",
        fullName: "Daniel Martin",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "identityVerification",
        password: "c87de541ae...",
        phoneNumber: "+2348045671234",
        profilePhoto: "https://example.com/photo8.jpg",
        referralCode: "daniel234",
        role: "Mechanic",
        userId: "user3456789",
        userType: "client",
    },
    {
        currentAddress: "Randle Avenue, Lagos, Nigeria",
        currentLoc: [6.5086416, 3.3569935],
        dateCreated: "17 June 2024 at 17:48:17 UTC+1",
        email: "Lolu1.jr@gmail.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-DfBE:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Olalekan Lawal",
        gender: "Male",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "workProof",
        password:
            "f272cccf4c96daa92540a9c52bc3e12ca811c33cbcad38cd99bd6325faf48b58",
        phoneNumber: "+2347063100898",
        profilePhoto:
            "https://firebasestorage.googleapis.com/v0/b/projob-server.appspot.com/o/passportPhotographs%2F3P9mWnmBvnYslXFGtFXZXjhlWHp2%2Fgs34kvz3q9.jpg?alt=media&token=70ab2f92-e0c3-4d0f-bbde-01045ba5dd82",
        referralCode: "lol0361e",
        role: "Hairstylist",
        userId: "3P9mWnmBvnYslXFGtFXZXjhlWHp2",
        userType: "provider",
    },
    {
        currentAddress: "23, Awolowo Road, Ikoyi, Lagos, Nigeria",
        currentLoc: [6.4546416, 3.4169935],
        dateCreated: "20 June 2024 at 14:20:17 UTC+1",
        email: "Yinka4real@gmail.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-DfBE:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Ayomide Oyedepo",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "paymentMethod",
        password:
            "f272cccf4c96daa92540a9c52bc3e12ca811c33cbcad38cd99bd6325faf48b58",
        phoneNumber: "+2348123456789",
        profilePhoto: "(link unavailable)",
        referralCode: "ayo0361e",
        role: "Makeup Artist",
        userId: "4P9mWnmBvnYslXFGtFXZXjhlWHp3",
        userType: "provider",
    },
];

export const providersData = [
    {
        currentAddress: "63870 Williams Wall, West Amybury, WY 41382",
        currentLoc: [-3.149024, 125.632861],
        dateCreated: "14 August 2024 at 21:04:44 UTC+1",
        email: "shields.carter@example.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-32dfda08:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Michael Jones",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "workProof",
        password:
            "f004c3273de9f327db60d07e6e23dcbf887a962ce89df4f202489c344f343de9",
        phoneNumber: "(370) 448-0527",
        profilePhoto: "",
        referralCode: "pzx4579",
        role: "Electrician",
        userId: "882be1a018d64eb68f58d2e7386d8009",
        userType: "provider",
    },
    {
        currentAddress: "23 Martins Road, Lagos, Nigeria",
        currentLoc: [6.5243793, 3.3792057],
        dateCreated: "12 February 2024 at 08:30:15 UTC+1",
        email: "john.doe@gmail.com",
        fcmToken: "fcmToken1:APA91bH....",
        fullName: "John Doe",
        gender: "Male",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "completed",
        password: "d56ab543edf92...",
        phoneNumber: "+2347012345678",
        profilePhoto: "https://example.com/photo1.jpg",
        referralCode: "john123",
        role: "Photographer",
        userId: "user123456",
        userType: "provider",
    },
    {
        currentAddress: "4 Broad Street, Abuja, Nigeria",
        currentLoc: [9.057851, 7.49508],
        dateCreated: "22 April 2024 at 10:00:00 UTC+1",
        email: "emma.williams@gmail.com",
        fcmToken: "fcmToken3:APA91bH....",
        fullName: "Emma Williams",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: false,
        onboardingLevel: "workProof",
        password: "e89df452b9...",
        phoneNumber: "+2349098765432",
        profilePhoto: "https://example.com/photo3.jpg",
        referralCode: "emma789",
        role: "Tutor",
        userId: "user345678",
        userType: "provider",
    },
    {
        currentAddress: "56 Garki, Abuja, Nigeria",
        currentLoc: [9.054267, 7.488566],
        dateCreated: "5 May 2024 at 14:25:40 UTC+1",
        email: "alex.brown@gmail.com",
        fcmToken: "fcmToken4:APA91bH....",
        fullName: "Alex Brown",
        gender: "Male",
        isCertified: false,
        isPhoneVerified: true,
        onboardingLevel: "profileSetup",
        password: "c92ab543df...",
        phoneNumber: "+2348123456789",
        profilePhoto: "https://example.com/photo4.jpg",
        referralCode: "alex234",
        role: "Plumber",
        userId: "user567890",
        userType: "provider",
    },
    {
        currentAddress: "10 Trans-Amadi, Port Harcourt, Nigeria",
        currentLoc: [4.815554, 7.049844],
        dateCreated: "10 June 2024 at 11:20:50 UTC+1",
        email: "lucy.green@gmail.com",
        fcmToken: "fcmToken5:APA91bH....",
        fullName: "Lucy Green",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "completed",
        password: "d91fb543ce...",
        phoneNumber: "+2348061234567",
        profilePhoto: "https://example.com/photo5.jpg",
        referralCode: "lucy567",
        role: "Chef",
        userId: "user7890123",
        userType: "provider",
    },
    {
        currentAddress: "8 Aba Road, Port Harcourt, Nigeria",
        currentLoc: [4.797016, 7.013506],
        dateCreated: "25 August 2024 at 13:30:20 UTC+1",
        email: "sophia.adams@gmail.com",
        fcmToken: "fcmToken7:APA91bH....",
        fullName: "Sophia Adams",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: false,
        onboardingLevel: "workProof",
        password: "d59ac542be...",
        phoneNumber: "+2347081234567",
        profilePhoto: "https://example.com/photo7.jpg",
        referralCode: "sophia789",
        role: "Hairdresser",
        userId: "user1234567",
        userType: "provider",
    },
    {
        currentAddress: "Randle Avenue, Lagos, Nigeria",
        currentLoc: [6.5086416, 3.3569935],
        dateCreated: "17 June 2024 at 17:48:17 UTC+1",
        email: "Lolu1.jr@gmail.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-DfBE:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Olalekan Lawal",
        gender: "Male",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "workProof",
        password:
            "f272cccf4c96daa92540a9c52bc3e12ca811c33cbcad38cd99bd6325faf48b58",
        phoneNumber: "+2347063100898",
        profilePhoto:
            "https://firebasestorage.googleapis.com/v0/b/projob-server.appspot.com/o/passportPhotographs%2F3P9mWnmBvnYslXFGtFXZXjhlWHp2%2Fgs34kvz3q9.jpg?alt=media&token=70ab2f92-e0c3-4d0f-bbde-01045ba5dd82",
        referralCode: "lol0361e",
        role: "Hairstylist",
        userId: "3P9mWnmBvnYslXFGtFXZXjhlWHp2",
        userType: "provider",
    },
    {
        currentAddress: "23, Awolowo Road, Ikoyi, Lagos, Nigeria",
        currentLoc: [6.4546416, 3.4169935],
        dateCreated: "20 June 2024 at 14:20:17 UTC+1",
        email: "Yinka4real@gmail.com",
        fcmToken:
            "fir21AS7QAq6vWG7R-DfBE:APA91bFWKNBKF9CgM8jedtF1tGAcPD3dryY2bIUhVk307CB2fIhI7ypbCO9nwnFAvh4Rz6UeetIXs47KPw9oKHExDaotXRDEWMyYC9aPrXMAFTCh-KDK6jU",
        fullName: "Ayomide Oyedepo",
        gender: "Female",
        isCertified: true,
        isPhoneVerified: true,
        onboardingLevel: "paymentMethod",
        password:
            "f272cccf4c96daa92540a9c52bc3e12ca811c33cbcad38cd99bd6325faf48b58",
        phoneNumber: "+2348123456789",
        profilePhoto: "(link unavailable)",
        referralCode: "ayo0361e",
        role: "Makeup Artist",
        userId: "4P9mWnmBvnYslXFGtFXZXjhlWHp3",
        userType: "provider",
    },
];

export const courseData = [
    {
        title: "Artificial Intelligence Masterclass",
        duration: 60,
        teacher: "Dr. Rachel Kim",
        enrolledStudents: 120,
        description:
            "Learn AI fundamentals, machine learning, and deep learning.",
        objectives: "Understand AI concepts, build intelligent systems.",
        targetAudience: "Beginners, programmers, data scientists.",
        format: "Video lectures, quizzes, projects.",
        language: "English",
        level: "Intermediate",
        rating: 4.8,
        price: 129.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=1",
    },
    {
        title: "Deep Learning with Python",
        duration: 30,
        teacher: "John Lee",
        enrolledStudents: 80,
        description: "Build deep learning models using Python and TensorFlow.",
        objectives: "Understand neural networks, natural language processing.",
        targetAudience: "Intermediate programmers, data scientists.",
        format: "Video lectures, coding exercises.",
        language: "English",
        level: "Advanced",
        rating: 4.9,
        price: 99.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=2",
    },
    {
        title: "Computer Vision Fundamentals",
        duration: 45,
        teacher: "Dr. Maria Rodriguez",
        enrolledStudents: 60,
        description: "Learn computer vision concepts, image processing.",
        objectives: "Understand object detection, segmentation.",
        targetAudience: "Beginners, programmers.",
        format: "Video lectures, quizzes.",
        language: "English",
        level: "Beginner",
        rating: 4.7,
        price: 79.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=3",
    },
    {
        title: "Natural Language Processing (NLP)",
        duration: 90,
        teacher: "Dr. David Kim",
        enrolledStudents: 100,
        description: "Learn NLP concepts, text analysis.",
        objectives: "Understand sentiment analysis, topic modeling.",
        targetAudience: "Intermediate programmers, data scientists.",
        format: "Video lectures, projects.",
        language: "English",
        level: "Intermediate",
        rating: 4.8,
        price: 149.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=4",
    },
    {
        title: "AI Ethics and Bias",
        duration: 20,
        teacher: "Dr. Sophia Patel",
        enrolledStudents: 40,
        description: "Understand AI ethics, bias, fairness.",
        objectives: "Develop responsible AI systems.",
        targetAudience: "AI professionals, ethicists.",
        format: "Video lectures, discussions.",
        language: "English",
        level: "Advanced",
        rating: 4.9,
        price: 49.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=5",
    },

    {
        title: "Robotics Engineering",
        duration: 60,
        teacher: "Dr. John Taylor",
        enrolledStudents: 80,
        description: "Design and develop intelligent robotic systems.",
        objectives: "Understand robotics fundamentals, control systems.",
        targetAudience: "Intermediate engineers, robotics enthusiasts.",
        format: "Video lectures, projects, simulations.",
        language: "English",
        level: "Advanced",
        rating: 4.8,
        price: 199.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=6",
    },
    {
        title: "AI for Healthcare",
        duration: 30,
        teacher: "Dr. Emily Chen",
        enrolledStudents: 100,
        description: "Apply AI in medical diagnosis, treatment.",
        objectives: "Understand healthcare AI applications.",
        targetAudience: "Medical professionals, health informatics.",
        format: "Video lectures, case studies.",
        language: "English",
        level: "Intermediate",
        rating: 4.7,
        price: 149.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=7",
    },
    {
        title: "Machine Learning with R",
        duration: 45,
        teacher: "Dr. Michael Brown",
        enrolledStudents: 60,
        description: "Build machine learning models using R.",
        objectives: "Understand supervised, unsupervised learning.",
        targetAudience: "Intermediate programmers, data analysts.",
        format: "Video lectures, coding exercises.",
        language: "English",
        level: "Intermediate",
        rating: 4.6,
        price: 99.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=8",
    },
    {
        title: "Computer Networks and Cybersecurity",
        duration: 90,
        teacher: "Dr. David Lee",
        enrolledStudents: 120,
        description: "Understand network fundamentals, security threats.",
        objectives: "Design secure network architectures.",
        targetAudience: "Intermediate network administrators.",
        format: "Video lectures, simulations.",
        language: "English",
        level: "Advanced",
        rating: 4.8,
        price: 249.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=9",
    },
    {
        title: "Data Visualization with Tableau",
        duration: 20,
        teacher: "Dr. Sophia Patel",
        enrolledStudents: 80,
        description: "Create interactive data visualizations.",
        objectives: "Understand data storytelling principles.",
        targetAudience: "Data analysts, business intelligence.",
        format: "Video lectures, projects.",
        language: "English",
        level: "Beginner",
        rating: 4.7,
        price: 79.99,
        enrollmentDate: "Anytime",
        certificate: true,
        imageUrl: "https://picsum.photos/200/300?random=10",
    },
];
